import { getDb } from './db';
import bcrypt from 'bcryptjs';

const ALL_CARS = [
    {
        id: 1,
        name: 'Mercedes-Benz S-Class',
        category: 'Sedán de Lujo',
        image: '/car-sedan.jpg',
        price: 850000,
        seats: 5,
        transmission: 'Automático',
        fuel: 'Gasolina',
        features: ['WiFi', 'A/C', 'GPS', 'Cuero', 'Sonido Burmester'],
        description: 'El epítome del lujo alemán. Tecnología de punta, confort excepcional y elegancia inigualable.',
        year: 2024,
        available: true,
    },
    {
        id: 2,
        name: 'Range Rover Vogue',
        category: 'SUV Premium',
        image: '/car-suv.jpg',
        price: 1200000,
        seats: 7,
        transmission: 'Automático',
        fuel: 'Diesel',
        features: ['WiFi', 'A/C', 'GPS', 'Panorámico', 'Aire suspensión'],
        description: 'La SUV más emblemática del mundo. Capacidad todoterreno con lujo británico.',
        year: 2024,
        available: true,
    },
    {
        id: 3,
        name: 'BMW M4 Competition',
        category: 'Deportivo',
        image: '/car-coupe.jpg',
        price: 950000,
        seats: 4,
        transmission: 'Automático',
        fuel: 'Gasolina',
        features: ['WiFi', 'A/C', 'GPS', 'Sonido Premium', 'Modo Sport+'],
        description: 'Rendimiento extremo con 510 CV. La deportividad alemana en su máxima expresión.',
        year: 2024,
        available: true,
    },
    {
        id: 4,
        name: 'Jaguar F-Type Convertible',
        category: 'Convertible',
        image: '/car-convertible.jpg',
        price: 1100000,
        seats: 2,
        transmission: 'Automático',
        fuel: 'Gasolina',
        features: ['WiFi', 'A/C', 'GPS', 'Descapotable', 'Escape deportivo'],
        description: 'Diseño británico atrevido con techo descapotable. Disfruta del viento en tu cara.',
        year: 2024,
        available: true,
    },
    {
        id: 5,
        name: 'Porsche Panamera',
        category: 'Sedán Deportivo',
        image: '/car-porsche.jpg',
        price: 980000,
        seats: 4,
        transmission: 'Automático',
        fuel: 'Gasolina',
        features: ['WiFi', 'A/C', 'GPS', 'Sport Chrono', 'PDK'],
        description: 'La perfecta combinación entre deportividad y lujo. Un 4 puertas con alma de 911.',
        year: 2024,
        available: true,
    },
    {
        id: 6,
        name: 'Lamborghini Urus',
        category: 'Super SUV',
        image: '/car-lambo.jpg',
        price: 1800000,
        seats: 5,
        transmission: 'Automático',
        fuel: 'Gasolina',
        features: ['WiFi', 'A/C', 'GPS', 'Modo Corsa', '650 CV'],
        description: 'La Super SUV más rápida del mundo. 650 CV de pura adrenalina italiana.',
        year: 2024,
        available: true,
    },
    {
        id: 7,
        name: 'Rolls Royce Ghost',
        category: 'Ultra Lujo',
        image: '/car-rolls.jpg',
        price: 3500000,
        seats: 5,
        transmission: 'Automático',
        fuel: 'Gasolina',
        features: ['WiFi', 'A/C', 'GPS', 'Estrellas', 'Puertas suicida'],
        description: 'El pináculo del lujo automotriz. Experiencia de conducción silenciosa y majestuosa.',
        year: 2024,
        available: true,
    },
    {
        id: 8,
        name: 'Ferrari 488 GTB',
        category: 'Supercar',
        image: '/car-ferrari.jpg',
        price: 2200000,
        seats: 2,
        transmission: 'Automático',
        fuel: 'Gasolina',
        features: ['WiFi', 'A/C', 'GPS', 'Modo Race', 'V8 Biturbo'],
        description: 'Icono italiano con motor V8 biturbo. 670 CV de pasión roja.',
        year: 2024,
        available: true,
    },
    {
        id: 9,
        name: 'Audi R8 V10',
        category: 'Supercar',
        image: '/car-audi-r8.jpg',
        price: 1950000,
        seats: 2,
        transmission: 'Automático',
        fuel: 'Gasolina',
        features: ['WiFi', 'A/C', 'GPS', 'V10', 'Quattro'],
        description: 'El superdeportivo alemán con motor V10. Tecnología quattro para máximo agarre.',
        year: 2024,
        available: true,
    },
    {
        id: 10,
        name: 'Bentley Continental GT',
        category: 'Gran Turismo',
        image: '/car-bentley.jpg',
        price: 2800000,
        seats: 4,
        transmission: 'Automático',
        fuel: 'Gasolina',
        features: ['WiFi', 'A/C', 'GPS', 'W12', 'Mulliner'],
        description: 'El gran turismo británico por excelencia. Lujo y potencia en perfecta armonía.',
        year: 2024,
        available: true,
    },
    {
        id: 11,
        name: 'Maserati Quattroporte',
        category: 'Sedán de Lujo',
        image: '/car-maserati.jpg',
        price: 890000,
        seats: 5,
        transmission: 'Automático',
        fuel: 'Gasolina',
        features: ['WiFi', 'A/C', 'GPS', 'Sonido Bowers', 'Italiano'],
        description: 'Sedán italiano con alma deportiva. El lujo mediterráneo en su máxima expresión.',
        year: 2024,
        available: true,
    },
    {
        id: 12,
        name: 'Tesla Model S Plaid',
        category: 'Eléctrico',
        image: '/car-tesla.jpg',
        price: 750000,
        seats: 5,
        transmission: 'Automático',
        fuel: 'Eléctrico',
        features: ['WiFi', 'A/C', 'GPS', 'Autopilot', '1020 CV'],
        description: 'El sedán eléctrico más rápido del mundo. 0-100 en 2 segundos. Futuro en movimiento.',
        year: 2024,
        available: true,
    },
    {
        id: 13,
        name: 'Cadillac Escalade',
        category: 'SUV Premium',
        image: '/car-escalade.jpg',
        price: 1100000,
        seats: 7,
        transmission: 'Automático',
        fuel: 'Gasolina',
        features: ['WiFi', 'A/C', 'GPS', 'Pantalla 38"', 'Americano'],
        description: 'El SUV americano más icónico. Presencia imponente y lujo sin límites.',
        year: 2024,
        available: true,
    },
    {
        id: 14,
        name: 'McLaren 720S',
        category: 'Supercar',
        image: '/car-mclaren.jpg',
        price: 2400000,
        seats: 2,
        transmission: 'Automático',
        fuel: 'Gasolina',
        features: ['WiFi', 'A/C', 'GPS', '720 CV', 'Monocasco'],
        description: 'Ingeniería británica extrema. 720 CV de pura emoción en un monocasco de carbono.',
        year: 2024,
        available: true,
    },
    {
        id: 15,
        name: 'Aston Martin DB11',
        category: 'Gran Turismo',
        image: '/car-aston.jpg',
        price: 1650000,
        seats: 4,
        transmission: 'Automático',
        fuel: 'Gasolina',
        features: ['WiFi', 'A/C', 'GPS', 'V8', 'James Bond'],
        description: 'El auto de James Bond. Elegancia británica con potencia deportiva.',
        year: 2024,
        available: true,
    },
    {
        id: 16,
        name: 'Lexus LX 600',
        category: 'SUV Premium',
        image: '/car-lexus.jpg',
        price: 980000,
        seats: 7,
        transmission: 'Automático',
        fuel: 'Gasolina',
        features: ['WiFi', 'A/C', 'GPS', 'Japonés', 'Fiabilidad'],
        description: 'Lujo japonés con fiabilidad legendaria. Confort y capacidad todoterreno.',
        year: 2024,
        available: true,
    },
    {
        id: 17,
        name: 'BMW X7',
        category: 'SUV Premium',
        image: '/car-x7.jpg',
        price: 1050000,
        seats: 7,
        transmission: 'Automático',
        fuel: 'Gasolina',
        features: ['WiFi', 'A/C', 'GPS', '7 plazas', 'Aleman'],
        description: 'El SUV más grande de BMW. Lujo y espacio para toda la familia.',
        year: 2024,
        available: true,
    },
    {
        id: 18,
        name: 'Mercedes G-Wagon G63',
        category: 'Super SUV',
        image: '/car-gwagon.jpg',
        price: 2100000,
        seats: 5,
        transmission: 'Automático',
        fuel: 'Gasolina',
        features: ['WiFi', 'A/C', 'GPS', 'AMG', 'Icono'],
        description: 'El icono del off-road de lujo. Diseño atemporal con potencia AMG.',
        year: 2024,
        available: true,
    },
    {
        id: 19,
        name: 'Chevrolet Corvette C8',
        category: 'Deportivo',
        image: '/car-corvette.jpg',
        price: 720000,
        seats: 2,
        transmission: 'Automático',
        fuel: 'Gasolina',
        features: ['WiFi', 'A/C', 'GPS', 'V8', 'Americano'],
        description: 'El superdeportivo americano accesible. Motor central V8 de alto rendimiento.',
        year: 2024,
        available: true,
    },
    {
        id: 20,
        name: 'Mercedes AMG GT',
        category: 'Deportivo',
        image: '/car-amggt.jpg',
        price: 1450000,
        seats: 2,
        transmission: 'Automático',
        fuel: 'Gasolina',
        features: ['WiFi', 'A/C', 'GPS', 'AMG', 'Biturbo'],
        description: 'El deportivo AMG con motor biturbo. Agresividad alemana pura.',
        year: 2024,
        available: true,
    },
    {
        id: 21,
        name: 'Porsche Cayenne Coupe',
        category: 'SUV Deportivo',
        image: '/car-cayenne.jpg',
        price: 920000,
        seats: 5,
        transmission: 'Automático',
        fuel: 'Gasolina',
        features: ['WiFi', 'A/C', 'GPS', 'Coupe', 'Porsche'],
        description: 'El SUV deportivo de Porsche. Diseño coupé con dinámica de 911.',
        year: 2024,
        available: true,
    },
    {
        id: 22,
        name: 'BMW Serie 7',
        category: 'Sedán de Lujo',
        image: '/car-bmw7.jpg',
        price: 880000,
        seats: 5,
        transmission: 'Automático',
        fuel: 'Gasolina',
        features: ['WiFi', 'A/C', 'GPS', 'Pantalla trasera', 'Aleman'],
        description: 'La berlina de lujo de BMW. Tecnología de vanguardia y confort supremo.',
        year: 2024,
        available: true,
    },
    {
        id: 23,
        name: 'Volvo XC90',
        category: 'SUV Premium',
        image: '/car-volvo.jpg',
        price: 780000,
        seats: 7,
        transmission: 'Automático',
        fuel: 'Híbrido',
        features: ['WiFi', 'A/C', 'GPS', 'Seguridad', 'Sueco'],
        description: 'El SUV más seguro del mundo. Diseño escandinavo y tecnología híbrida.',
        year: 2024,
        available: true,
    },
    {
        id: 24,
        name: 'Porsche 911 Turbo S',
        category: 'Supercar',
        image: '/car-911.jpg',
        price: 1850000,
        seats: 4,
        transmission: 'Automático',
        fuel: 'Gasolina',
        features: ['WiFi', 'A/C', 'GPS', 'Turbo S', 'Icono'],
        description: 'El icono deportivo por excelencia. 650 CV de pura adrenalina alemana.',
        year: 2024,
        available: true,
    },
    {
        id: 25,
        name: 'Audi A8 L',
        category: 'Sedán de Lujo',
        image: '/car-a8.jpg',
        price: 820000,
        seats: 5,
        transmission: 'Automático',
        fuel: 'Gasolina',
        features: ['WiFi', 'A/C', 'GPS', 'Matrix LED', 'Aleman'],
        description: 'La berlina de lujo de Audi. Tecnología matrix y confort de primera clase.',
        year: 2024,
        available: true,
    },
];

async function seed() {
    console.log('🌱 Starting DB seed...');
    const db = await getDb();

    // Create default admin
    const adminId = crypto.randomUUID();
    const hashedPassword = await bcrypt.hash('admin123', 10);

    await db.run(
        `INSERT OR IGNORE INTO users (id, name, email, password, phone, role) VALUES (?, ?, ?, ?, ?, ?)`,
        [
            adminId,
            'Administrador',
            'admin@carrentalmedellin.com',
            hashedPassword,
            '+57 300 000 0000',
            'admin'
        ]
    );
    console.log('✅ Admin user created/verified');

    // Insert cars
    let insertedCars = 0;
    for (const car of ALL_CARS) {
        const existing = await db.get('SELECT id FROM cars WHERE id = ?', [car.id]);
        if (!existing) {
            await db.run(
                `INSERT INTO cars (id, name, category, image, price, seats, transmission, fuel, features, description, year, available)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
                [
                    car.id,
                    car.name,
                    car.category,
                    car.image,
                    car.price,
                    car.seats,
                    car.transmission,
                    car.fuel,
                    JSON.stringify(car.features),
                    car.description,
                    car.year,
                    car.available ? 1 : 0
                ]
            );
            insertedCars++;
        }
    }
    console.log(`✅ Seeded ${insertedCars} new cars.`);
    console.log('🌱 Seed complete!');
}

seed().catch(console.error);
